#@server = https://davidcaldas934-humble-succotash-5wppp57r55r2qxq-8080.preview.app.github.dev
@server = https://ec03-g9r7.onrender.com
@apiserver = {{server}}/api/instrumento
###
GET {{server}}
###
GET {{apiserver}}/listar
###
POST {{apiserver}}/nuevo
Content-Type: application/x-www-form-urlencoded

nombre=Saxofon
###
DELETE {{apiserver}}/eliminar
Content-Type: application/x-www-form-urlencoded

id=52
###


